---
title: "Strawberries"
author: "Ajay Krishnakumar"
date: 2023 Oct 23
format: pdf
engine: knitr
---

## Introduction: The data, the motivations

When was the last time you looked at your strawberries - not just a cursory examination before you ate them, but really looked? At the labels, at the warnings and cautions and USDA certifications and the chemicals they spray on them? I had certainly never considered any of those factors until this assignment, until we were told that perhaps this was something to look into, until Haviland Wright painted for us the extent to which strawberries are not to be trusted.

-   What sort of chemicals are being used on strawberries?
-   How hazardous are these chemicals?
-   Where are these chemicals used most

Considering the consistent placing of Strawberries on the 'Dirty Dozen' list, these are but a few of the questions we should think about.  As consumers we should be concerned about the extensive use of pesticide in daily foods. As human beings with our instinct for self-preservation, we should be concerned about the chemicals we are putting in our bodies. So what can the data tell us? How alarmed should we be? I'll try to answer that first question. The second is left as an exercise for the reader. 

The data itself is from the USDA NASS database, cleaned through much effort by Haviland(though perhaps not one hundredth of the effort we should put into cleaning our strawberries if the results of this exercise are anything to go by). It is this data collected by survey instead of census and focusing on non organic strawberries that serves as the jumping off point for what follows.

## Data Cleaning and Organization

The first order of business is to split the data that remains from the earlier cleaning into
